// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  device

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( RegisterDeviceReq ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RegisterDeviceReq ) UnmarshalJSON([]byte) error { return nil }
func ( RegisterDeviceReq ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* RegisterDeviceReq ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RegisterDeviceReq *RegisterDeviceReq
