// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package music

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson66c1e240DecodeGitRonaksoftwareComBlipServerPkgMusic(in *jlexer.Lexer, out *SearchReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "keyword":
			out.Keyword = string(in.String())
		case "artist":
			out.Artist = string(in.String())
		case "lyrics":
			out.Lyrics = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson66c1e240EncodeGitRonaksoftwareComBlipServerPkgMusic(out *jwriter.Writer, in SearchReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"keyword\":"
		out.RawString(prefix[1:])
		out.String(string(in.Keyword))
	}
	if in.Artist != "" {
		const prefix string = ",\"artist\":"
		out.RawString(prefix)
		out.String(string(in.Artist))
	}
	if in.Lyrics != "" {
		const prefix string = ",\"lyrics\":"
		out.RawString(prefix)
		out.String(string(in.Lyrics))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SearchReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson66c1e240EncodeGitRonaksoftwareComBlipServerPkgMusic(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SearchReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson66c1e240EncodeGitRonaksoftwareComBlipServerPkgMusic(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SearchReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson66c1e240DecodeGitRonaksoftwareComBlipServerPkgMusic(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SearchReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson66c1e240DecodeGitRonaksoftwareComBlipServerPkgMusic(l, v)
}
