// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  music

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Song ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Song ) UnmarshalJSON([]byte) error { return nil }
func ( Song ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Song ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Song *Song
