// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package music

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson366630dfDecodeGitRonaksoftwareComBlipServerPkgMusic(in *jlexer.Lexer, out *Song) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ID).UnmarshalJSON(data))
			}
		case "title":
			out.Title = string(in.String())
		case "genre":
			out.Genre = string(in.String())
		case "lyrics":
			out.Lyrics = string(in.String())
		case "artists":
			out.Artists = string(in.String())
		case "cover_url":
			out.CoverUrl = string(in.String())
		case "song_url":
			out.SongUrl = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson366630dfEncodeGitRonaksoftwareComBlipServerPkgMusic(out *jwriter.Writer, in Song) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Raw((in.ID).MarshalJSON())
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"genre\":"
		out.RawString(prefix)
		out.String(string(in.Genre))
	}
	{
		const prefix string = ",\"lyrics\":"
		out.RawString(prefix)
		out.String(string(in.Lyrics))
	}
	{
		const prefix string = ",\"artists\":"
		out.RawString(prefix)
		out.String(string(in.Artists))
	}
	{
		const prefix string = ",\"cover_url\":"
		out.RawString(prefix)
		out.String(string(in.CoverUrl))
	}
	{
		const prefix string = ",\"song_url\":"
		out.RawString(prefix)
		out.String(string(in.SongUrl))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Song) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson366630dfEncodeGitRonaksoftwareComBlipServerPkgMusic(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Song) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson366630dfEncodeGitRonaksoftwareComBlipServerPkgMusic(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Song) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson366630dfDecodeGitRonaksoftwareComBlipServerPkgMusic(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Song) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson366630dfDecodeGitRonaksoftwareComBlipServerPkgMusic(l, v)
}
