// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  msg

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( ResponseEnvelope ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ResponseEnvelope ) UnmarshalJSON([]byte) error { return nil }
func ( ResponseEnvelope ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ResponseEnvelope ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ResponseEnvelope *ResponseEnvelope
