// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package msg

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3bd68309DecodeGitRonaksoftwareComBlipServerPkgMsg(in *jlexer.Lexer, out *ResponseEnvelope) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "constructor":
			out.Constructor = string(in.String())
		case "payload":
			if m, ok := out.Payload.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Payload.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Payload = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3bd68309EncodeGitRonaksoftwareComBlipServerPkgMsg(out *jwriter.Writer, in ResponseEnvelope) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"constructor\":"
		out.RawString(prefix[1:])
		out.String(string(in.Constructor))
	}
	{
		const prefix string = ",\"payload\":"
		out.RawString(prefix)
		if m, ok := in.Payload.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Payload.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Payload))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResponseEnvelope) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3bd68309EncodeGitRonaksoftwareComBlipServerPkgMsg(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResponseEnvelope) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3bd68309EncodeGitRonaksoftwareComBlipServerPkgMsg(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResponseEnvelope) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3bd68309DecodeGitRonaksoftwareComBlipServerPkgMsg(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResponseEnvelope) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3bd68309DecodeGitRonaksoftwareComBlipServerPkgMsg(l, v)
}
