// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  acr

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Music ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Music ) UnmarshalJSON([]byte) error { return nil }
func ( Music ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Music ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Music *Music
