// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  auth

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( AccessTokenCreated ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AccessTokenCreated ) UnmarshalJSON([]byte) error { return nil }
func ( AccessTokenCreated ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AccessTokenCreated ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AccessTokenCreated *AccessTokenCreated

func ( Authorization ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Authorization ) UnmarshalJSON([]byte) error { return nil }
func ( Authorization ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Authorization ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Authorization *Authorization

func ( CreateAccessToken ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CreateAccessToken ) UnmarshalJSON([]byte) error { return nil }
func ( CreateAccessToken ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CreateAccessToken ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CreateAccessToken *CreateAccessToken

func ( LoginReq ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* LoginReq ) UnmarshalJSON([]byte) error { return nil }
func ( LoginReq ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* LoginReq ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_LoginReq *LoginReq

func ( LogoutReq ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* LogoutReq ) UnmarshalJSON([]byte) error { return nil }
func ( LogoutReq ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* LogoutReq ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_LogoutReq *LogoutReq

func ( PhoneCodeSent ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PhoneCodeSent ) UnmarshalJSON([]byte) error { return nil }
func ( PhoneCodeSent ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PhoneCodeSent ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PhoneCodeSent *PhoneCodeSent

func ( RegisterReq ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RegisterReq ) UnmarshalJSON([]byte) error { return nil }
func ( RegisterReq ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* RegisterReq ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RegisterReq *RegisterReq

func ( SendCodeReq ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SendCodeReq ) UnmarshalJSON([]byte) error { return nil }
func ( SendCodeReq ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SendCodeReq ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SendCodeReq *SendCodeReq
