// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package saba

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (ConfirmResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ConfirmResponse) UnmarshalJSON([]byte) error        { return nil }
func (ConfirmResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ConfirmResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ConfirmResponse *ConfirmResponse

func (SendSmsResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*SendSmsResponse) UnmarshalJSON([]byte) error        { return nil }
func (SendSmsResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*SendSmsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SendSmsResponse *SendSmsResponse

func (SubscribeResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*SubscribeResponse) UnmarshalJSON([]byte) error        { return nil }
func (SubscribeResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*SubscribeResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SubscribeResponse *SubscribeResponse

func (UnsubscribeResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*UnsubscribeResponse) UnmarshalJSON([]byte) error        { return nil }
func (UnsubscribeResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*UnsubscribeResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UnsubscribeResponse *UnsubscribeResponse
