// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  admin

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( HealthCheckStats ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* HealthCheckStats ) UnmarshalJSON([]byte) error { return nil }
func ( HealthCheckStats ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* HealthCheckStats ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_HealthCheckStats *HealthCheckStats

func ( SetVasReq ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SetVasReq ) UnmarshalJSON([]byte) error { return nil }
func ( SetVasReq ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SetVasReq ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SetVasReq *SetVasReq

func ( Unsubscribed ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Unsubscribed ) UnmarshalJSON([]byte) error { return nil }
func ( Unsubscribed ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Unsubscribed ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Unsubscribed *Unsubscribed
