// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  store

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Store ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Store ) UnmarshalJSON([]byte) error { return nil }
func ( Store ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Store ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Store *Store
