// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package crawler

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3c9d2b01DecodeGitRonaksoftwareComBlipServerPkgCrawler(in *jlexer.Lexer, out *SearchResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "req_id":
			out.RequestID = string(in.String())
		case "source":
			out.Sources = string(in.String())
		case "result":
			easyjson3c9d2b01Decode(in, &out.Result)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGitRonaksoftwareComBlipServerPkgCrawler(out *jwriter.Writer, in SearchResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"req_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.RequestID))
	}
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		out.String(string(in.Sources))
	}
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix)
		easyjson3c9d2b01Encode(out, in.Result)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SearchResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGitRonaksoftwareComBlipServerPkgCrawler(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SearchResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGitRonaksoftwareComBlipServerPkgCrawler(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SearchResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGitRonaksoftwareComBlipServerPkgCrawler(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SearchResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGitRonaksoftwareComBlipServerPkgCrawler(l, v)
}
func easyjson3c9d2b01Decode(in *jlexer.Lexer, out *struct {
	SongUrl  string `json:"song_url"`
	CoverUrl string `json:"cover_url"`
	Lyrics   string `json:"lyrics,omitempty"`
	Artists  string `json:"artists"`
	Title    string `json:"title"`
	Genre    string `json:"genre"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "song_url":
			out.SongUrl = string(in.String())
		case "cover_url":
			out.CoverUrl = string(in.String())
		case "lyrics":
			out.Lyrics = string(in.String())
		case "artists":
			out.Artists = string(in.String())
		case "title":
			out.Title = string(in.String())
		case "genre":
			out.Genre = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01Encode(out *jwriter.Writer, in struct {
	SongUrl  string `json:"song_url"`
	CoverUrl string `json:"cover_url"`
	Lyrics   string `json:"lyrics,omitempty"`
	Artists  string `json:"artists"`
	Title    string `json:"title"`
	Genre    string `json:"genre"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"song_url\":"
		out.RawString(prefix[1:])
		out.String(string(in.SongUrl))
	}
	{
		const prefix string = ",\"cover_url\":"
		out.RawString(prefix)
		out.String(string(in.CoverUrl))
	}
	if in.Lyrics != "" {
		const prefix string = ",\"lyrics\":"
		out.RawString(prefix)
		out.String(string(in.Lyrics))
	}
	{
		const prefix string = ",\"artists\":"
		out.RawString(prefix)
		out.String(string(in.Artists))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"genre\":"
		out.RawString(prefix)
		out.String(string(in.Genre))
	}
	out.RawByte('}')
}
func easyjson3c9d2b01DecodeGitRonaksoftwareComBlipServerPkgCrawler1(in *jlexer.Lexer, out *SearchRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "req_id":
			out.RequestID = string(in.String())
		case "keyword":
			out.Keyword = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeGitRonaksoftwareComBlipServerPkgCrawler1(out *jwriter.Writer, in SearchRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"req_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.RequestID))
	}
	{
		const prefix string = ",\"keyword\":"
		out.RawString(prefix)
		out.String(string(in.Keyword))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SearchRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeGitRonaksoftwareComBlipServerPkgCrawler1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SearchRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeGitRonaksoftwareComBlipServerPkgCrawler1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SearchRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeGitRonaksoftwareComBlipServerPkgCrawler1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SearchRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeGitRonaksoftwareComBlipServerPkgCrawler1(l, v)
}
