// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
	"fmt"
	"os"

	"github.com/mailru/easyjson/gen"

	pkg "git.ronaksoftware.com/blip/server/pkg/help"
)

func main() {
	g := gen.NewGenerator("messages_easyjson.go")
	g.SetPkg("help", "git.ronaksoftware.com/blip/server/pkg/help")
	g.Add(pkg.EasyJSON_exporter_Config(nil))
	g.Add(pkg.EasyJSON_exporter_SetDefaultConfig(nil))
	if err := g.Run(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
