// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  help

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Config ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Config ) UnmarshalJSON([]byte) error { return nil }
func ( Config ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Config ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Config *Config

func ( Feedback ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Feedback ) UnmarshalJSON([]byte) error { return nil }
func ( Feedback ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Feedback ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Feedback *Feedback

func ( SetDefaultConfig ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SetDefaultConfig ) UnmarshalJSON([]byte) error { return nil }
func ( SetDefaultConfig ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SetDefaultConfig ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SetDefaultConfig *SetDefaultConfig

func ( UnsetDefaultConfig ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* UnsetDefaultConfig ) UnmarshalJSON([]byte) error { return nil }
func ( UnsetDefaultConfig ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* UnsetDefaultConfig ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UnsetDefaultConfig *UnsetDefaultConfig
