version: '2'
services:

  # MongoDB Server
  mongo:
    restart: always
    image: registry.ronaksoftware.com/base/mongo:4.0
    volumes:
      - ./_hdd/db-mongo:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017
    networks:
      - blip

networks:
  blip:
    external:
      name: blip